### ISSUE TITLE
Class names

### ISSUE THREAD

**Issue by elliottheis** [skyglobal/web-toolkit#192]
I'm thinking of giving some of the class names some more thought particularly surrounding typography.

Currently it's a bit hard to consume typographic aspects of the toolkit given their current class naming convention, as presently their names seem to work well for article style pages with classes such as 'intro' however when you start to move away from this sort of  page style your html becomes semantically confusing; as the classes you're applying do not describe the actual style, so I'm proposing we also add extra class to mitigate this issue.

Keen to hear everyone's thoughts.

**Comment by peter-mouland** [comment]
new components use BEM
