### ISSUE TITLE
Distribution/consumability

### ISSUE THREAD

**Issue by elliottheis** [skyglobal/web-toolkit#194]
It might be time to start to discuss other consumption options of the toolkit. 

So... to kick it off...

I'm guessing for a reasonable number of consumers, most styles probably aren't used, and therefore it might be unnecessary for clients to be downloading all these unused styles... An idea might be to introduce things like silent classes into the toolkit, so it can be easily consumed as an SCSS mixin library however obviously you wouldn't get the added benefits such as the CDN etc, but it does then allow teams to be have cleaner semantics.

**Comment by peter-mouland** [comment]
sorted with the new use of bower and separating components
