### ISSUE TITLE
rename 'share' to 'action links'

### ISSUE THREAD

**Issue by ninadel** [skyglobal/web-toolkit#220]
would recommend renaming the 'share' component to 'action links' as this pattern will cover actions beyond sharing (e.g. 'record' and 'never miss')

**Comment by peter-mouland** [comment]
i'm closing this as the current use is just for share and haven't seen any new designs on how to use it for remote record etc.   share is available here http://skyglobal.github.io/share/ so feel free to reopen an issue there
