### ISSUE TITLE
Get CircleCI to do pull requests too

### ISSUE THREAD

**Issue by bjfletcher** [skyglobal/web-toolkit#230]
Goal: I am a Toolkit contributer, I submit a pull request, and CircleCI builds, tests & deploys the pull request branch to S3.

Perhaps with authorized list of users such as skyguide.

**Comment by peter-mouland** [comment]
testing sorted for all pull requests, i think auto deploy is a bit much :)
```
First login to CircleCI and select the repo you wish to configure. On this page you will see the results of all previous builds. In the upper right hand coner click on the gear, representing settings. Select "experimental settings" under "tweaks." Next, turn on the "Project fork pull requests" setting
```
