### ISSUE TITLE
RequireJS load errors

### ISSUE THREAD

**Issue by bjfletcher** [skyglobal/web-toolkit#241]
1. go here http://web-toolkit.global.sky.com/2.2.13-rc-v2/_site/index.html 
2. open the JS console
3. keep hitting reload button while keeping an eye on the JS console
4. hopefully sometimes you'll see the error below:

```
GET http://web-toolkit.global.sky.com/2.2.13-rc-v2/_site/dist/demo/scripts/toolkit/components/in-page-nav.js 403 (Forbidden) require-2.1.9.min.js:34
Uncaught Error: Script error for: components/in-page-nav
http://requirejs.org/docs/errors.html#scripterror require-2.1.9.min.js:8
GET http://web-toolkit.global.sky.com/2.2.13-rc-v2/_site/dist/demo/scripts/toolkit/utils/hash-manager.js 403 (Forbidden) require-2.1.9.min.js:34
Uncaught Error: Script error for: utils/hash-manager
http://requirejs.org/docs/errors.html#scripterror require-2.1.9.min.js:8
```

Question of the day: why are these modules URLed for when they are already included in `toolkit.js`?

Another question: is it a bug with the demo page setup?

**Comment by peter-mouland** [comment]
i cant see this in the latest version
