### ISSUE TITLE
Mis-aligned icons with Toolkit 2.3

### ISSUE THREAD

**Issue by bjfletcher** [skyglobal/web-toolkit#297]
- [ ] carousel arrows need to be a bit higher (or the semi-transparent background) and left a bit.

- [ ] the popup share icon needs to be higher

- [ ] the "share this page" has underlined icons on hover

- [ ] the tooltip hover "i" icon needs to be a bit higher

anything else?

**Comment by peter-mouland** [comment]
i'm gonna close this issue as it potentially relates to many components - not skycons
