### ISSUE TITLE
Check Mark Issue

### ISSUE THREAD

**Issue by Malcolm-M** [skyglobal/web-toolkit#310]
Hi, when using the relevant skycons font and \e027 we are seeing a clock face as opposed to the check mark which should appear. This was only after recent changes to the version.
We have to use CSS as there is no access to the HTML on the community platform.
.MobileTkbArticlePage div.lia-message-template-solution-zone > h2:first-child:before {
content: "\E027";
padding-right: 4px;
font-family: "skycons";
font-size: 16px;
line-height: 30px;
color: #fff !important;
}

**Comment by peter-mouland** [comment]
Hi Malcom,

The code for the skycons have been moved out of the toolkit, into its own component so you can now consume skycons individually or as you have been as a part of the whole toolkit.  This means if you use sass for your css, you could use a mixin from the skycons source code and have less stuff harcoded as the font codes are likely to change.

However, Looking at the demo page for that (http://skyglobal.github.io/skycons/) it looks like your code provided should work.  What version of the toolkit are you using?

**Comment by Malcolm-M** [comment]
Hi,
Response from the team member who handles the versions is below. Is this likely to be the cause?

“We’re using /dist/1173 for skycons currently, we could switch to the latest version but that would mean changing CSS for all icons in use across the site as all references appear to have changed with the latest build."

Malcolm McGeachy
Channel Development Team
Service Support
07738 855590
malcolm.mcgeachy@bskyb.com
3 Macintosh Road, Kirkton Campus, Livingston, West Lothian, EH54 7BW

**Comment by peter-mouland** [comment]
I was expecting to see something like : 
```
http://web-toolkit.global.sky.com/2.3.0/fonts/skycons.min.css
``` 
or  
```
http://web-toolkit.global.sky.com/components/skycons/0.2.0/css/skycons.css
```
Is `dist/1173` the version of the masthead you are using? I know the masthead have what they have confusingly name `skyicons` to differentiate from `skycons`.  This is a tiny subset of icons used within the masthead so that there was no dependency on a specific version of the skycons just for the masthead.

I'll raise an issue with the team that does the masthead and ask them to name it to something more descriptive.  In the meantime you should either move to use [Skycons](https://github.com/skyglobal/skycons) directly.

**Comment by damnhipster** [comment]
As far as I know, the latest version of skycons is backwards compatible with the web-toolkit v2.0.

**Comment by Malcolm-M** [comment]
Hi Robert,
Was 1173 the masthead version?

Malcolm McGeachy
Channel Development Team
Service Support
07738 855590
malcolm.mcgeachy@bskyb.com
3 Macintosh Road, Kirkton Campus, Livingston, West Lothian, EH54 7BW

**Comment by Malcolm-M** [comment]
Hi, yes that was the masthead. Is pulling the fonts in via the masthead and directly likely to pose any issues?

Malcolm McGeachy
Channel Development Team
Service Support
07738 855590
malcolm.mcgeachy@bskyb.com
3 Macintosh Road, Kirkton Campus, Livingston, West Lothian, EH54 7BW

**Comment by peter-mouland** [comment]
no issue, thats why they are named differently - to avoid conflict.
