### ISSUE TITLE
skycons cors error

### ISSUE THREAD

**Issue by sabeurthabti** [skyglobal/web-toolkit#312]
Calling the fonts from a none sky.com domain is giving a cors error, can we allow bskyb domains to call the toolkit?

**Comment by peter-mouland** [comment]
yup - i noticed this recently too, i think it worked before.
is worth checking the akamai config...

**Comment by sabeurthabti** [comment]
So this is happening because on the new componetized version : http://web-toolkit.global.sky.com/2.3.5/fonts/skycons.css

notice:
`/*../fonts/*/
@font-face {
  font-family: "skycons";
  src: url('../fonts/skycons.eot');
  src: url('../fonts/skycons.eot?#iefix') format('eot'), url('../fonts/skycons.woff') format('woff'), url('../fonts/skycons.ttf') format('truetype'), url('../fonts/skycons.svg#skycons') format('svg'); }
`

compared to the one before: http://web-toolkit.global.sky.com/2.3.2/fonts/skycons.css

`/* Generated by grunt-webfont */
/* Based on https://github.com/endtwist/fontcustom/blob/master/lib/fontcustom/templates/fontcustom.css */
@font-face {
    font-family:"skycons";
    src:url("skycons.eot");
    font-weight:normal;
    font-style:normal;
}`

I will investigate it further but if anyone is having an issue, please point your skycons css to `2.3.2`.

**Comment by peter-mouland** [comment]
i think this has been fixed with an akamai config update. if anyone still has a problem feel free to re-open
