### ISSUE TITLE
In-page nav: make ids in URL hash more deterministic

### ISSUE THREAD

**Issue by charypar** [skyglobal/web-toolkit#314]
The hashbang url for individual tabs sometimes changes across browsers and devices, so you can't use it to send someone a link to a particular section of the page. 

To reproduce, copy a url to a tab and reopen it in a private browsing mode or a different browser/device. Sometimes the first tab will be selected and the url of the originally selected tab will be different. Here are the two URLs I got for the same tab on the same page in testing the problem:

* <http://help.sky.com/articles/sky-go-supported-devices#!whole-nav-76364000d2-computer>
* <http://help.sky.com/articles/sky-go-supported-devices#!whole-nav-e9aac0b075-computer>

Just out of interest, how are those numbers generated?

**Comment by peter-mouland** [comment]
those id's will be generated by the help app.

The in-page-nav just provides a method as to save state i..e you register a JS function against a particular hash (or hash partial).  When that hash is matched within the url, the function will be executed; in this case to load the correct tab.

**Comment by charypar** [comment]
Oh sorry, didn't realise it's us generating those ids! Thanks for clearing that up.
